FROM golang:1.24.3-alpine3.21 as builder

RUN go install github.com/air-verse/air@latest

WORKDIR /src

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download

CMD ["air", "-c", ".air.toml"]
